version: "3"
services:
  java-springboot:
    image: java-springboot
    ports:
      - "8083:8086"
    networks:
      - mynetwork
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  employee-mysql: 